# This is a generated file. Not intended for manual editing.
services:
  evently.api:
    build:
      context: "/home/masoud/CE/Projects/Evently"
      dockerfile: "src/API/Evently.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/Evently.API.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "evently.api:dev"
    ports: []
    volumes:
    - "/home/masoud/CE/Projects/Evently/src/API/Evently.API:/app:rw"
    - "/home/masoud/CE/Projects/Evently:/src:rw"
    - "/home/masoud/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
